// Writes index.d.ts from index.js, so the types are exactly the values.
//   node packages/domain/gen-dts.mjs
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import * as domain from './index.js'

export function renderDts() {
  const lit = (v) => `'${v}'`
  const tuple = (a) => `readonly [${a.map(lit).join(', ')}]`
  const lines = ['// Generated by gen-dts.mjs from index.js. Do not edit by hand.', '']
  // Sorted: Node and Vite list a module's exports in different orders.
  for (const [name, value] of Object.entries(domain).sort(([a], [b]) => a.localeCompare(b))) {
    if (Array.isArray(value)) {
      lines.push(`export declare const ${name}: ${tuple(value)}`)
    } else {
      const body = Object.entries(value).map(([k, v]) => `  readonly ${k}: ${tuple(v)}`).join('\n')
      lines.push(`export declare const ${name}: {\n${body}\n}`)
    }
  }
  return lines.join('\n') + '\n'
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)), 'index.d.ts'), renderDts())
}
